
import type { Product } from './types'

// A tiny catalog to start. Replace with API later.
export const PRODUCTS: Product[] = [
  // Ayurvedic Products - Tablets
  {
    id: 'P_AYUR_T_01',
    slug: 'alfalfa-1x-weakness-medicine',
    name: 'Alfalfa 1X: Ayurvedic Medicine For Weakness in Old Age',
    brand: 'AyurArogya',
    category: 'Ayurvedic',
    subcategory: 'Ayurvedic Medicine',
    tertiaryCategory: 'Tablets',
    image: 'https://ik.imagekit.io/b5qewhvhb/e%20commers/ayrvedic%20medicines/Tablets/alfalfa-1X-300x300.jpg',
    quantity: 50,
    price: { original: 100, currency: '₹' },
    shortDescription: 'Helps in gaining weight by supplementing essential elements in the body.',
    description: 'शरीर में कमजोरी महसूस होने पर, इसका सेवन वैद्यकीय सलाह अनुसार करने से शरीर में आवश्यक तत्वों की कमी पूरी करके वजन बढ़ाने में यह टैबलेट सहायक है । दुबले पतले व कमजोर शरीर या किसी भी रोग के बाद आयी कमजोरी या भूख की कमी में तथा स्तनपान कराने वाली माताओं एवं शिशु आदि में पाचन को दुरुस्त करके शरीर का उचित पोषण करके वजन बढ़ाता है।',
    specifications: { weight: '30g', 'Dosage': '1-1 टैब दिन में तीन बार चूसकर या चिकित्सक की सलाह अनुसार।' },
    features: ['100% Natural and Pure Products', '100% Secure Payments', 'Efficient Price'],
    inventory: { inStock: true },
    ratings: { average: 4.5, count: 15 },
    returnPolicy: { eligible: false },
    codAvailable: true,
  },
  {
    id: 'P_AYUR_T_02',
    slug: 'madhu-nashini-diabetes-tablet',
    name: 'Madhu Nashini (Diabetes) Tablet',
    brand: 'AyurArogya',
    category: 'Ayurvedic',
    subcategory: 'Ayurvedic Medicine',
    tertiaryCategory: 'Tablets',
    image: 'https://ik.imagekit.io/b5qewhvhb/e%20commers/ayrvedic%20medicines/Tablets/1660407050madhunashinigutika-300x300.webp',
    quantity: 50,
    price: { original: 50, currency: '₹' },
    shortDescription: 'Quickly controls diabetes and overcomes physical weakness caused by it.',
    description: 'मधुमेह (डायबिटीज मेलिटस) को तुरंत कंट्रोल करके डायबिटीज के कारण आने वाली शारीरिक कमजोरी को दूर करके नस-नाड़ियों को ताकत देती है । इसका प्रयोग शुरू करने के 2-3 दिन में ही आशातीत लाभ नज़र आने लगते हैं । यह निर्दोष आयुर्वेदिक औषधि कोई भी दुष्प्रभाव (साइड इफेक्ट) नहीं करती है ।',
    specifications: { weight: '75g', 'Composition': 'गोझरण घन, कुटकी, नीम, तुलसी, चिरायता' , 'Dosage': '2-2 गोली खाली पेट दिन में तीन बार सादे पानी के साथ लें ।' },
    features: ['100% Natural and Pure Products', '100% Secure Payments', 'Efficient Price'],
    inventory: { inStock: true },
    ratings: { average: 4.8, count: 45 },
    returnPolicy: { eligible: false },
    codAvailable: true,
  },
  {
    id: 'P_AYUR_T_03',
    slug: 'gaujharan-ghanvati-gomutra-tablet',
    name: 'Purified Gaujharan GhanVati | Gomutra Tablet',
    brand: 'Achyutaya',
    category: 'Ayurvedic',
    subcategory: 'Ayurvedic Medicine',
    tertiaryCategory: 'Tablets',
    image: 'https://ik.imagekit.io/b5qewhvhb/e%20commers/ayrvedic%20medicines/Tablets/1640267374gaujharanghanvati-300x300.webp',
    quantity: 50,
    price: { original: 50, currency: '₹' },
    shortDescription: 'Useful in a variety of ailments including cough, asthma, diabetes, and skin disorders.',
    description: 'लाभ : कफ के रोग, वायु केरोग, पेट के रोग, अग्निमांधघुटनोका का दर्द, अजीर्ण, आफरासंग्रहनी,लीवर के रोग, पीलिया(कमला), प्लीहा के रोग, डायबिटीज, बहुमुत्रता, शोथ, जोड़ोका का दर्द, कैंसर, गठिया, बदन दर्द, कृमि, बच्चोंके रोग, कान के रोग, टी.बी, स्त्री रोग, सिरदर्द आदि में उपयोगी',
    specifications: { weight: '100g', 'Main Ingredients': 'Concentrated cow urine (gaujaran ghan), Terminalia chebula (Harad), Cassia angustifolia (Sanay) etc' , 'Dosage': '2 से 4 गोली पानी केसाथ दिन में दो बार ले सकते है ।' },
    features: ['100% Natural and Pure Products', '100% Secure Payments', 'Efficient Price'],
    inventory: { inStock: true },
    ratings: { average: 4.6, count: 30 },
    returnPolicy: { eligible: false },
    codAvailable: true,
  },
  {
    id: 'P_AYUR_T_04',
    slug: 'samshamani-vati-immunity',
    name: 'Samshamani Vati (30 Tablets) – Ayurvedic Vati',
    brand: 'AyurArogya',
    category: 'Ayurvedic',
    subcategory: 'Ayurvedic Medicine',
    tertiaryCategory: 'Tablets',
    image: 'https://ik.imagekit.io/b5qewhvhb/e%20commers/ayrvedic%20medicines/Tablets/1594909945Giloy_Vati-300x300.webp',
    quantity: 50,
    price: { original: 20, currency: '₹' },
    shortDescription: 'Helps in boosting immunity and protecting from infectious diseases.',
    description: 'रोगप्रतिरोधक शक्ति (Immunity Power) बढ़ाने में लाभदायी । यह जीवाणु (Bacteria), विषाणु (Virus) आदि के कारण होनेवाले संक्रामक रोगों से सुरक्षा में सहायक है । यह वटी श्वसन तंत्र (Respiratory System) को मजबूत बनाकर सर्दी-जुकाम (Rhinorrhea), खाँसी (Cough), बुखार (Fever) आदि संक्रमण जन्य (Infectious Disease) रोगों से सुरक्षा प्रदान करती है ।',
    specifications: { weight: '70g', 'Dosage': '12 साल से ऊपर 2-2 गोली सुबह-शाम खाली पेट में शहद या गर्म पानी से लें ।' },
    features: ['100% Natural and Pure Products', '100% Secure Payments', 'Efficient Price'],
    inventory: { inStock: true },
    ratings: { average: 4.7, count: 80 },
    returnPolicy: { eligible: false },
    codAvailable: true,
  },
  {
    id: 'P_AYUR_T_05',
    slug: 'suraksha-vati-antibiotic',
    name: 'Suraksha Vati: Natural Ayurvedic Antibiotic Tablet',
    brand: 'AyurArogya',
    category: 'Ayurvedic',
    subcategory: 'Ayurvedic Medicine',
    tertiaryCategory: 'Tablets',
    image: 'https://ik.imagekit.io/b5qewhvhb/e%20commers/ayrvedic%20medicines/Tablets/suraksha-vati.webp',
    quantity: 0,
    price: { original: 60, currency: '₹' },
    shortDescription: 'Enhances immunity and protects against infectious diseases.',
    description: 'श्रेष्ठ एंटीबायोटिक तुलसी, यकृत (लिवर) की कार्यक्षमता बढ़ाने वाली गिलोय सत्व व उत्तम ज्वरनाशक किराततिक्त के मिश्रण से बनी यह सुरक्षा वटी व्याधि प्रतिकार क्षमता बढ़ाकर संक्रामक तथा अन्य अनेक रोगों से सुरक्षा करती है । पाचनशक्ति बढ़ाकर सार रूप नवधातुओं के निर्माण में मदद करती है ।',
    specifications: { weight: '50-60g', 'Ingredients': 'तुलसी, गिलोय सत्व व किराततिक्त (चिरायता) आदि', 'Dosage': 'सुबह – शाम 1 से 2 गोलियाँ बड़ों के लिए, बालकों के लिए 1/2 से 1 गोली पानी के साथ ।' },
    features: ['100% Natural and Pure Products', '100% Secure Payments', 'Efficient Price'],
    inventory: { inStock: false },
    ratings: { average: 4.8, count: 55 },
    returnPolicy: { eligible: false },
    codAvailable: true,
  },
  {
    id: 'P_AYUR_T_06',
    slug: 'original-shilajit-capsules',
    name: '100% Original Shilajit Tablet/Capsules',
    brand: 'AyurArogya',
    category: 'Ayurvedic',
    subcategory: 'Ayurvedic Medicine',
    tertiaryCategory: 'Tablets',
    image: 'https://ik.imagekit.io/b5qewhvhb/e%20commers/ayrvedic%20medicines/Tablets/shilajit-scaled-e1695145059206-300x300.jpg',
    quantity: 0,
    price: { original: 80, currency: '₹' },
    shortDescription: 'Used to boost energy and revitalize the body with strong antioxidant properties.',
    description: 'सदियों से, आयुर्वेदिक दवाओं के चिकित्सकों ने ऊर्जा को बढ़ावा देने और शरीर को पुनर्जन्मित करने के लिए शिलाजीत का उपयोग किया है । शरीर के भीतर मिटोकोंड्रिया के कार्य को बढ़ाकर यह शरीर को ऊर्जा प्रदान करता है । यह जड़ी बूटी शरीर को मजबूत एंटीऑक्सिडेंट गुणों के साथ पुनर्जीवित करती है ।',
    specifications: { weight: '20g', 'Contains': '20 Pieces', 'Dosage': 'सुबह-शाम 1-1 कैप्सूल प्रतिदिन 2 बार ले सकते हैं ।' },
    features: ['100% Natural and Pure Products', '100% Secure Payments', 'Efficient Price'],
    inventory: { inStock: false },
    ratings: { average: 5.0, count: 1 },
    returnPolicy: { eligible: false },
    codAvailable: true,
  },
  {
    id: 'P_AYUR_T_07',
    slug: 'ashwagandha-tablet',
    name: '100% Pure Ashwagandha Tablet',
    brand: 'AyurArogya',
    category: 'Ayurvedic',
    subcategory: 'Ayurvedic Medicine',
    tertiaryCategory: 'Tablets',
    image: 'https://ik.imagekit.io/b5qewhvhb/e%20commers/ayrvedic%20medicines/Tablets/1738481679Ashwagandha_tablet-300x300.webp',
    quantity: 0,
    price: { original: 80, currency: '₹' },
    shortDescription: 'A powerful tonic that strengthens nerves and muscles and helps in increasing height.',
    description: 'अश्वगंधा एक बलवर्धक व पुष्टिदायक श्रेष्ठ रसायन है । यह मधुर व स्निग्ध होने के कारण वात शमन करने वाला एवं रस- रक्तादि सप्तधातुओं का पोषण करने वाला है । इससे विशेषत: मांस व शुक्रधातु की वृद्धि होती है ।',
    specifications: { weight: '100g', 'Ingredients': 'Withania Somnifera Ashwagandha 90%, Zea Manys 10%', 'Dosage': '2 से 4 गोली सुबह-शाम खाली पेट मिश्री युक्त गुनगुने दूध के साथ लें ।' },
    features: ['100% Natural and Pure Products', '100% Secure Payments', 'Efficient Price'],
    inventory: { inStock: false },
    ratings: { average: 5.0, count: 1 },
    returnPolicy: { eligible: false },
    codAvailable: true,
  },
  {
    id: 'P_AYUR_T_08',
    slug: 'triphala-with-honey-tablet',
    name: '100% Pure Ayurvedic Triphala with Honey Tablet (Goli)',
    brand: 'AyurArogya',
    category: 'Ayurvedic',
    subcategory: 'Ayurvedic Medicine',
    tertiaryCategory: 'Tablets',
    image: 'https://ik.imagekit.io/b5qewhvhb/e%20commers/ayrvedic%20medicines/Tablets/shahadyukta-trifala-tablet-300x300.jpg',
    quantity: 50,
    price: { original: 50, currency: '₹' },
    shortDescription: 'Beneficial for the eyes, improves complexion and voice, and acts as an aphrodisiac.',
    description: 'यह गोली श्रेष्ठ रसायन, बलप्रद एवं पौष्टिक है । यह नेत्रों के लिए हितकर, वर्ण एवं स्वर को उत्तम करनेवाली, वीर्यवर्धक, भूख बढ़ानेवाली एवं रुचिकारक है । इसके नियमित सेवन से मस्तिष्क – रोग, दंतरोग, हृदयरोग एवं गुर्दों की विभिन्न बीमारियों से रक्षा होती है ।',
    specifications: { weight: '100g', 'Ingredients': 'Emblica officimalis:30%, Honey:40%, Terinalia belerica:20%, Terinalia chebula:10%', 'Dosage': '2 से 3 गोलियाँ रात को सोते समय या सुबह खाली पेट पानी से लें ।' },
    features: ['100% Natural and Pure Products', '100% Secure Payments', 'Efficient Price'],
    inventory: { inStock: true },
    ratings: { average: 4.7, count: 22 },
    returnPolicy: { eligible: false },
    codAvailable: true,
  },
  {
    id: 'P_AYUR_T_09',
    slug: 'hira-bhasma-vajra-rasayan-tablet',
    name: '100% Pure Hira Bhasma [Vajra Rasayan Tablet]',
    brand: 'AyurArogya',
    category: 'Ayurvedic',
    subcategory: 'Ayurvedic Medicine',
    tertiaryCategory: 'Tablets',
    image: 'https://ik.imagekit.io/b5qewhvhb/e%20commers/ayrvedic%20medicines/Tablets/vajrarasayan-tablet-300x300.jpg',
    quantity: 50,
    price: { original: 175, currency: '₹' },
    shortDescription: 'Makes the body strong as a diamond. It is a Tridosha-shamak and an excellent tonic.',
    description: 'शरीर को वज्र के समान मजबूत बनाता है । यह त्रिदोषशामक एवं उत्तम रसायन है । दूषित कोशिकाओं को हटाकर नयी कोशिकाओं का निर्माण करने में सहायक है । यह शुक्राणु उत्पन्न करनेवाली, ग्रंथियों को बल देनेवाली एवं नपुंसकता में अद्वितीय औषधि है ।',
    specifications: { weight: '50g', 'Ingredients': 'हीरे की भस्म, गिलोय, आँवला आदि रसायन', 'Dosage': 'स्वस्थ व्यक्ति शारीरिक बल बढ़ाने हेतु सर्दियों में आधी से १ गोली दिन में एक या दो बार दूध, मलाई, घी, शहद, किशमिश के रस या गुलकंद के साथ ले ।' },
    features: ['100% Natural and Pure Products', '100% Secure Payments', 'Efficient Price'],
    inventory: { inStock: true },
    ratings: { average: 4.9, count: 40 },
    returnPolicy: { eligible: false },
    codAvailable: true,
  },
  {
    id: 'P_AYUR_T_10',
    slug: 'rajat-malti-tablet',
    name: '100% Pure Rajat Malti Tablet',
    brand: 'AyurArogya',
    category: 'Ayurvedic',
    subcategory: 'Ayurvedic Medicine',
    tertiaryCategory: 'Tablets',
    image: 'https://ik.imagekit.io/b5qewhvhb/e%20commers/ayrvedic%20medicines/Tablets/rajat-malti-tablet-300x300.jpg',
    quantity: 0,
    price: { original: 120, currency: '₹' },
    shortDescription: 'Increases blood, strengthens muscles. Boosts lifespan, virility, intelligence, and radiance.',
    description: 'रजत मालती टेबलेट रक्त को बढ़ाती है, मांसपेशियों को ताकत देती है । आयुष्य, वीर्य, बुद्धि और कांति को बढ़ाती है । क्रोध, श्रम, पढ़ाई, रात्रि-जागरण, मनन, सूर्यताप, शोक, भय आदि के कारण होने वाली वात-वृद्धि में खास फायदा करती है ।',
    specifications: { weight: '13.5g', 'Ingredients': 'रजत भस्म', 'Dosage': 'बच्चों के लिए आधी गोली एक बार । बड़ों के लिए 1 या 2 गोली 2 बार ।' },
    features: ['100% Natural and Pure Products', '100% Secure Payments', 'Efficient Price'],
    inventory: { inStock: false },
    ratings: { average: 4.8, count: 18 },
    returnPolicy: { eligible: false },
    codAvailable: true,
  },
  {
    id: 'P_AYUR_T_11',
    slug: 'suvarn-prash-tablet-swarna-bhasma',
    name: '100% Pure Suvarn Prash Tablet with Swarna Bhasma',
    brand: 'AyurArogya',
    category: 'Ayurvedic',
    subcategory: 'Ayurvedic Medicine',
    tertiaryCategory: 'Tablets',
    image: 'https://ik.imagekit.io/b5qewhvhb/e%20commers/ayrvedic%20medicines/Tablets/suvarnaprash-tab-300x300.jpg',
    quantity: 0,
    price: { original: 300, currency: '₹' },
    shortDescription: 'Helps in boosting Brain Memory Power and acts as an Energy Booster.',
    description: 'सुवर्ण भस्म पुष्य नक्षत्र में बनाई यह पुण्यदायी गोली आयु, शक्ति, मेधा, बुद्धि, कांति व जठराग्निवर्धक तथा ग्रहबाधा निवारक, उत्तम गर्भपोषक है । गर्भवती स्त्री इसका सेवन करके निरोगी, तेजस्वी, मेधावी संतति को जन्म दे सकती है ।',
    specifications: { weight: '9.5g', 'Ingredients': 'सुवर्ण भस्म, केसर, सुवर्ण माक्षिक भस्म, वाचा', 'Dosage': '≥ 5 साल – 2 टैब दिन में दो बार। गाय के दूध/घी के साथ खाली पेट या चिकित्सक के निर्देशानुसार।' },
    features: ['100% Natural and Pure Products', '100% Secure Payments', 'Efficient Price'],
    inventory: { inStock: false },
    ratings: { average: 4.9, count: 95 },
    returnPolicy: { eligible: false },
    codAvailable: true,
  },

  // Ayurvedic Products - Ark
  {
    id: 'P_AYUR_A_01',
    slug: 'arjun-gaujharan-ark',
    name: 'Arjun Gaujharan Ark',
    brand: 'AyurArogya',
    category: 'Ayurvedic',
    subcategory: 'Ayurvedic Medicine',
    tertiaryCategory: 'Ark',
    image: 'https://ik.imagekit.io/b5qewhvhb/e%20commers/ayrvedic%20medicines/Ark/1737106735arjun_gaujharan_ark_210ml-1-300x300.webp?updatedAt=1756360798431',
    quantity: 0,
    price: { original: 40, currency: '₹' },
    shortDescription: 'मोटापा एवं हृदय रोग हेतू।',
    description: 'हृदय के सभी रोग, क्षतक्षय, कांस, विष, रक्विकार, रक्तपित्त, प्रमेह, ज्वर एवं व्रण, अस्थि भग्न, शोध आदि रोगों में उपयोगी।',
    specifications: { weight: '490g', 'Net Volume': '210 ml', 'Dosage': '10 से 20 मिली अर्क 2-2 अर्जुन घनवटी के साथ खाली पेट कभी भी ले सकते हैं ।' },
    features: ['100% Natural and Pure Products', '100% Secure Payments', 'Efficient Price'],
    inventory: { inStock: false },
    ratings: { average: 4.6, count: 12 },
    returnPolicy: { eligible: false },
    codAvailable: true,
  },
  {
    id: 'P_AYUR_A_02',
    slug: 'adusa-ark-syrup',
    name: 'Adusa Ark (Syrup)',
    brand: 'AyurArogya',
    category: 'Ayurvedic',
    subcategory: 'Ayurvedic Medicine',
    tertiaryCategory: 'Ark',
    image: 'https://ik.imagekit.io/b5qewhvhb/e%20commers/ayrvedic%20medicines/Ark/adusa-ark-300x300.jpg?updatedAt=1756360798434',
    quantity: 50,
    price: { original: 40, currency: '₹' },
    shortDescription: 'लाभकारी इन नकसीर, रक्तपित्त, श्वास, कफ और खांसी।',
    description: 'नकसीर व रक्तपित्त, श्वास, कफ और खांसी की बीमारी में लाभकारी है । यह सर्दी-जुकाम के लिए भी लाभकारी हो सकता है । अडूसा में एंटी-एलर्जिक गुण मौजूद होते हैं ।',
    specifications: { 'Net Volume': '210ml', 'Dosage': '5 से 15 मिली. दिन में एक या दो बार खाली पेट पानी के साथ।' },
    features: ['100% Natural and Pure Products', '100% Secure Payments', 'Efficient Price'],
    inventory: { inStock: true },
    ratings: { average: 4.7, count: 25 },
    returnPolicy: { eligible: false },
    codAvailable: true,
  },
  {
    id: 'P_AYUR_A_03',
    slug: 'punarnava-ark-liver-kidney',
    name: 'Ayurvedic Punarnava Ark For Liver, Kidney Disorders',
    brand: 'AyurArogya',
    category: 'Ayurvedic',
    subcategory: 'Ayurvedic Medicine',
    tertiaryCategory: 'Ark',
    image: 'https://ik.imagekit.io/b5qewhvhb/e%20commers/ayrvedic%20medicines/Ark/punarnava-ark-300x300.jpg?updatedAt=1756360798417',
    quantity: 30,
    price: { original: 35, currency: '₹' },
    shortDescription: 'उत्तम शोथनाशक तथा पीलिया, रक्त की कमी, उदर रोग, मूत्रकृच्छ्र में उत्तम गुणकारी।',
    description: 'पुनर्नवा अर्क उत्तम शोथनाशक तथा पीलिया, रक्त की कमी, हलीमक, उदर रोग, मूत्रकृच्छ्र, प्रमेह, रक्तपित्त, वृक्क विकार (Kidney Disease ) यकृत् शोथ, बस्ति शोथ, गर्भाशय शोथ आदि विकारों में उत्तम गुणकारी है ।',
    specifications: { weight: '210ml or 500ml', 'Dosage': '2 तोला से 4 तोला, तीन से चार बार आधा तोला मधु मिलाकर या औषधियों के अनुपान रूप में प्रयोग करें ।' },
    variants: [ { size: '210ml', price: 35}, {size: '500ml', price: 60} ],
    features: ['100% Natural and Pure Products', '100% Secure Payments', 'Efficient Price'],
    inventory: { inStock: true },
    ratings: { average: 4.8, count: 40 },
    returnPolicy: { eligible: false },
    codAvailable: true,
  },
  {
    id: 'P_AYUR_A_04',
    slug: 'giloy-ark-juice',
    name: 'Giloy Ark Juice: For Immunity, Fever',
    brand: 'AyurArogya',
    category: 'Ayurvedic',
    subcategory: 'Ayurvedic Medicine',
    tertiaryCategory: 'Ark',
    image: 'https://ik.imagekit.io/b5qewhvhb/e%20commers/ayrvedic%20medicines/Ark/giloyadi-ark-300x300.jpg?updatedAt=1756360798433',
    quantity: 10,
    price: { original: 40, currency: '₹' },
    shortDescription: 'Boosts immunity, controls blood sugar, and improves digestion.',
    description: 'गिलोय क्रोनिक बुखार, डेंगू बुखार (प्लेटलेट काउंट बढ़ाकर), एलर्जिक राइनाइटिस, वायरस संक्रमण, रक्त शर्करा के स्तर को नियंत्रित करता है, प्रतिरक्षा को बढ़ावा देता है, पाचन में सुधार करता है, तनाव और चिंता को कम करता है, गठिया का इलाज करता है, आंखों में सुधार करता है ।',
    specifications: { 'Net Volume': '210ml', 'Ingredients': 'गिलोय, तुलसी, इलाइची, पानी' },
    features: ['100% Natural and Pure Products', '100% Secure Payments', 'Efficient Price'],
    inventory: { inStock: true, lowStockThreshold: 10 },
    ratings: { average: 4.9, count: 150 },
    returnPolicy: { eligible: false },
    codAvailable: true,
  },
  {
    id: 'P_AYUR_A_05',
    slug: 'neem-ark-leaves',
    name: 'Neem Ark (Neem Leaves)',
    brand: 'AyurArogya',
    category: 'Ayurvedic',
    subcategory: 'Ayurvedic Medicine',
    tertiaryCategory: 'Ark',
    image: 'https://ik.imagekit.io/b5qewhvhb/e%20commers/ayrvedic%20medicines/Ark/neem-ark-300x300.jpg?updatedAt=1756360798411',
    quantity: 100,
    price: { original: 30, currency: '₹' },
    shortDescription: 'रक्त को शुद्ध करने वाली बहुमूल्य औषधि।',
    description: 'आयुर्वेद के अनुसार नीम शीतल, पचने में हल्का, कफ-पित्तशामक व थकान, प्यास, खाँसी, बुखार, अरूचि, कृमि, घाव, उल्टी, जी मिचलाना, प्रमेह (मूत्र-संबंधी रोगों) आदि को दूर करने वाला है । नीम के पत्तों से बना यह अर्क रक्त को शुद्ध करने वाली बहुमूल्य औषधि है ।',
    specifications: { 'Dosage': '१० से ३० मि.ली. अर्क (बालकों हेतु २ से ५ मि.ली.) समभाग पानी मिलाकर दिन में २ बार लें ।', 'Ingredients': 'Neem (Azadirachta Indica): 2.5 ml, Water: Q.S.' },
    features: ['100% Natural and Pure Products', '100% Secure Payments', 'Efficient Price'],
    inventory: { inStock: true },
    ratings: { average: 4.7, count: 88 },
    returnPolicy: { eligible: false },
    codAvailable: true,
  },
  {
    id: 'P_AYUR_A_06',
    slug: 'pudina-ark-juice',
    name: 'Pudina Ark Juice',
    brand: 'AyurArogya',
    category: 'Ayurvedic',
    subcategory: 'Ayurvedic Medicine',
    tertiaryCategory: 'Ark',
    image: 'https://ik.imagekit.io/b5qewhvhb/e%20commers/ayrvedic%20medicines/Ark/pudina-ark-35-300x300.webp?updatedAt=1756360798436',
    quantity: 120,
    price: { original: 35, currency: '₹' },
    shortDescription: 'रुचिकारक, स्फूर्तिदायक, त्रिदोषशामक।',
    description: 'बहुत कम लोगों को ही पता है कि पुदीना ऐसी जड़ी बूटी है जो औषधि के रुप में काम करती है । पुदीना अपने वातशामक गुण के कारण बालों के रूखेपन को कम करने में सहयोग देता है ।',
    specifications: { 'Dosage': '10 ले 20 मि.ली. अर्क आवश्यकतानुसार जल के साथ लें । (बालकों हेतु 3 से 10 मि.ली.)' },
    features: ['100% Natural and Pure Products', '100% Secure Payments', 'Efficient Price'],
    inventory: { inStock: true },
    ratings: { average: 4.8, count: 95 },
    returnPolicy: { eligible: false },
    codAvailable: true,
  },
  {
    id: 'P_AYUR_A_07',
    slug: 'gomutra-ark-cow-urine',
    name: 'Purified Gomutra | Godhan Ark [Cow Urine]',
    brand: 'Achyutaya',
    category: 'Ayurvedic',
    subcategory: 'Ayurvedic Medicine',
    tertiaryCategory: 'Ark',
    image: 'https://ik.imagekit.io/b5qewhvhb/e%20commers/ayrvedic%20medicines/Ark/gaumutra-ark-300x300.jpg?updatedAt=1756360798461',
    quantity: 200,
    price: { original: 50, currency: '₹' },
    shortDescription: 'A biological tonic that helps in many diseases.',
    description: 'देशी गाय के गोमूत्र में कई उपयोगी तत्व पाए गए हैं, इसीलिए गोमूत्र के कई सारे फायदे हैं । गोमूत्र अर्क इन उपयोगी तत्वों के कारण इतना प्रसिद्ध है ।',
    specifications: { 'Dosage': '10 मि.ली. से 20 मि.ली. अर्क में 100 मि.ली. पानी मिलाकर खाली पेट कभी भी ले सकते हैं ।' },
    features: ['100% Natural and Pure Products', '100% Secure Payments', 'Efficient Price'],
    inventory: { inStock: true },
    ratings: { average: 4.9, count: 300 },
    returnPolicy: { eligible: false },
    codAvailable: true,
  },
  {
    id: 'P_AYUR_A_08',
    slug: 'tulsi-ark',
    name: 'Tulsi Ark',
    brand: 'Achyutaya',
    category: 'Ayurvedic',
    subcategory: 'Ayurvedic Medicine',
    tertiaryCategory: 'Ark',
    image: 'https://ik.imagekit.io/b5qewhvhb/e%20commers/ayrvedic%20medicines/Ark/Tulsi-Ark-Big-300x300.jpg?updatedAt=1756360798476',
    quantity: 80,
    price: { original: 40, currency: '₹' },
    shortDescription: 'Boosts immunity, balances blood sugar, and has anti-fungal properties.',
    description: 'तुलसी अर्क में तमाम तरह के औषधीय गुण मौजूद होते हैं । तुलसी का अर्क रोग प्रतिरोधक शक्ति को बेहतर करने में, खून में शुगर के स्तर को संतुलित रखने में तो सहायक होता ही है, इसके साथ ही इसमें एंटी पायरेटिक (बुखार कम करने वाला), एंटी कैंसर, एंटी फंगल गुण भी मौजूद है ।',
    variants: [ { size: '210ml', price: 40}, {size: '500ml', price: 90} ],
    specifications: { 'Dosage': '5 से 15 मिली. दिन में एक या दो बार खाली पेट पानी के साथ' },
    features: ['100% Natural and Pure Products', '100% Secure Payments', 'Efficient Price'],
    inventory: { inStock: true },
    ratings: { average: 4.9, count: 210 },
    returnPolicy: { eligible: false },
    codAvailable: true,
  },
  {
    id: 'P_AYUR_A_09',
    slug: 'gaumutra-sarpagandha-ark',
    name: 'Gaumutra Sarpagandha Ark',
    brand: 'Achyutaya',
    category: 'Ayurvedic',
    subcategory: 'Ayurvedic Medicine',
    tertiaryCategory: 'Ark',
    image: 'https://ik.imagekit.io/b5qewhvhb/e%20commers/ayrvedic%20medicines/Ark/gaumutra-sarpagandha-ark-300x300.jpg?updatedAt=1756360798459',
    quantity: 60,
    price: { original: 110, currency: '₹' },
    shortDescription: 'Useful in high BP, high fever, etc.',
    description: 'रक्तचाप, वातिक उन्माद, अनिद्रा, पागलपन, सभी प्रकार के मानसिक विकार, बालातिसार, हैजा, उदरशूल, रक्तातिसार, जीर्णज्वर आदि रोगों में उपयोगी ।',
    specifications: { 'Dosage': '10 से 20 मिली. अर्क 2-2 सर्पगंधा घनवटी के साथ खाली पेट ।' },
    features: ['100% Natural and Pure Products', '100% Secure Payments', 'Efficient Price'],
    inventory: { inStock: true },
    ratings: { average: 4.8, count: 55 },
    returnPolicy: { eligible: false },
    codAvailable: true,
  },

  // Fashion Products
  {
    id: 'P_FASH_M_01',
    slug: 'mens-ethnic-cotton-kurta',
    name: 'Men\'s Ethnic Cotton Kurta',
    brand: 'DesiWear',
    category: 'Fashion',
    subcategory: 'Men-Ethnic',
    image: 'https://images.unsplash.com/photo-1593032228653-25cb157b70a8?q=80&w=800&auto=format&fit=crop',
    extraImages: [
        'https://images.unsplash.com/photo-1617137968423-c6e4e242343a?q=80&w=800&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1617137968447-160aa2b7f032?q=80&w=800&auto=format&fit=crop'
    ],
    quantity: 150,
    price: { original: 1499, discounted: 799, currency: '₹' },
    description: 'A comfortable and stylish cotton kurta for men, perfect for festive occasions and casual wear. Made from high-quality fabric for a soft feel and elegant look.',
    shortDescription: 'Stylish & comfy cotton kurta for festive or casual wear.',
    features: ['100% premium cotton', 'Hand-stitched detailing', 'Breathable fabric'],
    specifications: { Fit: 'Regular', 'Sleeve Type': 'Full Sleeve', Care: 'Machine Wash' },
    ratings: { average: 4.5, count: 120 },
    codAvailable: true,
    returnPolicy: { eligible: true, duration: 10 },
    warranty: 'No Warranty',
    tags: ['kurta', 'ethnic wear', 'men fashion', 'desiwear']
  },
  {
    id: 'P_FASH_W_01',
    slug: 'womens-anarkali-kurta-set',
    name: 'Women\'s Anarkali Kurta Set',
    brand: 'DesiWear',
    category: 'Fashion',
    subcategory: 'Women-Ethnic',
    image: 'https://images.unsplash.com/photo-1622354223106-24c01798835d?q=80&w=800&auto=format&fit=crop',
    quantity: 80,
    price: { original: 2999, discounted: 1499, currency: '₹' },
    description: 'Elegant Anarkali kurta set for women, crafted from fine rayon fabric. Comes with a matching dupatta and churidar. Perfect for weddings and parties.',
    shortDescription: 'Elegant rayon Anarkali set with dupatta and churidar.',
    features: ['Soft rayon fabric', 'Intricate embroidery', 'Comes as a complete set'],
    specifications: { Fabric: 'Rayon', Style: 'Anarkali', 'Occasion': 'Festive' },
    ratings: { average: 4.8, count: 250 },
    codAvailable: true,
    returnPolicy: { eligible: true, duration: 10 },
    warranty: 'No Warranty',
    tags: ['anarkali', 'ethnic wear', 'women fashion', 'desiwear']
  },
  // Tech Products
  {
    id: 'P_TECH_M_01',
    slug: 'galaxy-a54-5g',
    name: 'Samsung Galaxy A54 5G (Awesome Violet, 8GB, 128GB Storage)',
    brand: 'Samsung',
    category: 'Tech',
    subcategory: 'Mobiles',
    image: 'https://images.unsplash.com/photo-1678830440338-467537a6a422?q=80&w=800&auto=format&fit=crop',
    extraImages: [
        'https://images.unsplash.com/photo-1678830440375-816783f289b4?q=80&w=800&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1678830440330-801262d9894f?q=80&w=800&auto=format&fit=crop'
    ],
    quantity: 100,
    price: { original: 41999, discounted: 35499, currency: '₹' },
    description: 'A well-balanced 5G smartphone with a vibrant AMOLED display, capable OIS camera, and a long-lasting battery. Features IP67 water resistance for added durability.',
    shortDescription: 'Bright AMOLED, OIS camera, all-day battery.',
    features: ['6.4" FHD+ Super AMOLED Display', '50MP OIS Main Camera', '5000mAh Battery', 'IP67 Water Resistant'],
    specifications: { RAM: '8 GB', ROM: '128 GB', 'Processor': 'Exynos 1380' },
    ratings: { average: 4.3, count: 4500 },
    codAvailable: true,
    returnPolicy: { eligible: true, duration: 7 },
    warranty: '1 Year Manufacturer Warranty',
    tags: ['samsung', 'galaxy', '5g', 'smartphone', 'android']
  },
  {
    id: 'P_TECH_M_02',
    slug: 'apple-iphone-15',
    name: 'Apple iPhone 15 (128 GB) - Blue',
    brand: 'Apple',
    category: 'Tech',
    subcategory: 'Mobiles',
    image: 'https://images.unsplash.com/photo-1700216223237-859c9a239af4?q=80&w=800&auto=format&fit=crop',
    quantity: 75,
    price: { original: 79900, currency: '₹' },
    description: 'The iPhone 15 brings you the Dynamic Island, a 48MP Main camera, and USB-C — all in a durable color-infused glass and aluminum design.',
    shortDescription: 'Dynamic Island, 48MP camera, USB-C.',
    features: ['6.1-inch Super Retina XDR display', 'Dynamic Island', 'A16 Bionic chip', 'USB-C connector'],
    specifications: { 'Display Size': '6.1 inches', 'Chip': 'A16 Bionic', 'Camera': '48MP Main' },
    ratings: { average: 4.7, count: 12000 },
    codAvailable: false,
    returnPolicy: { eligible: true, duration: 7 },
    warranty: '1 Year Apple Warranty',
    tags: ['apple', 'iphone', 'ios', 'smartphone']
  },
];

    